# golangci-lint 設定ファイル
# 対象: tools/wp-cli/

run:
  timeout: 3m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - unused
    - misspell
    - gosimple
    - typecheck
    - gosec
    - noctx

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/shiimanblog/wp-cli
  misspell:
    locale: US

issues:
  exclude-rules:
    # テストファイルではエラーチェックを緩和
    - path: _test\.go
      linters:
        - errcheck
    # main.go では未使用変数チェックを除外
    - path: main\.go
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 10
